services:
  alpha:
    build:
      context: ./alpha
    depends_on:
      - eureka
      - api-gateway
      - alpha-pg
      - kafka-1
    ports:
      - "8081:8081"
    networks:
      - isys3461_net
    env_file: .env
    environment:
      - POSTGRES_URI=jdbc:postgresql://alpha-pg:5432/ead_db?user=ead_user&password=ead_pwd

  alpha-pg:
    image: "postgres:17"
    ports:
      - "5442:5432"
    networks:
      - isys3461_net
    environment:
      - POSTGRES_DB=ead_db
      - POSTGRES_USER=ead_user
      - POSTGRES_PASSWORD=ead_pwd

  